In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
import statsmodels.formula.api as smf

In [9]:
df = pd.read_csv("Framingham-2-1.csv")

In [10]:
df.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4240.000000,4240.000000,4135.000000,4240.000000,4211.000000,4187.000000,4240.000000,4240.000000,4240.000000,4190.000000,4240.000000,4240.000000,4221.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,1.979444,0.494104,9.005937,0.029615,0.005896,0.310613,0.025708,236.699523,132.354599,82.897759,25.800801,75.878981,81.963655,0.151887
std,0.495027,8.572942,1.019791,0.500024,11.922462,0.169544,0.076569,0.462799,0.158280,44.591284,22.033300,11.910394,4.079840,12.025348,23.954335,0.358953
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,90.000000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [11]:
df[df['cigsPerDay'] == 70]

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
3008,1,40,3.0,1,70.0,0.0,0,1,0,210.0,132.0,86.0,31.57,98.0,80.0,0

In [12]:
#missing values, dropping any row that has no values
df = df.dropna()

In [14]:
df['TenYearCHD'].value_counts()

TenYearCHD
0    3101
1     557
Name: count, dtype: int64

In [13]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42,stratify=df['TenYearCHD'])

In [18]:
logistic_regression_1 = smf.logit(formula='TenYearCHD ~ age + totChol + sysBP + male', data=df_train).fit()
logistic_regression_1.summary()

Optimization terminated successfully.
         Current function value: 0.381876
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:             TenYearCHD   No. Observations:                 2926
Model:                          Logit   Df Residuals:                     2921
Method:                           MLE   Df Model:                            4
Date:                Wed, 28 Oct 2026   Pseudo R-squ.:                  0.1055
Time:                        19:02:00   Log-Likelihood:                -1117.4
converged:                       True   LL-Null:                       -1249.1
Covariance Type:            nonrobust   LLR p-value:                 8.220e-56
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -8.5571      0.501    -17.075      0.000      -9.539      -7.575
age            0.0604      0.007      8.775      0.000       0.047       0.074
totChol        0.0031      0.001      2.459      0.014       0.001       0.005
sysBP          0.0195      0.002      8.210      0.000       0.015       0.024
male           0.6466      0.112      5.787      0.000       0.428       0.866
==============================================================================
"""

In [21]:
independent_vars = list(df_train.columns)
independent_vars.remove('TenYearCHD')

In [22]:
" + ".join(independent_vars)

'male + age + education + currentSmoker + cigsPerDay + BPMeds + prevalentStroke + prevalentHyp + diabetes + totChol + sysBP + diaBP + BMI + heartRate + glucose'

In [26]:
logitformula = "TenYearCHD ~ " + " + ".join(independent_vars)

In [27]:
logistic_regression_final = smf.logit(formula=logitformula, data=df_train).fit()
print(logistic_regression_final.summary())

Optimization terminated successfully.
         Current function value: 0.374871
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:             TenYearCHD   No. Observations:                 2926
Model:                          Logit   Df Residuals:                     2910
Method:                           MLE   Df Model:                           15
Date:                Wed, 28 Oct 2026   Pseudo R-squ.:                  0.1219
Time:                        19:08:28   Log-Likelihood:                -1096.9
converged:                       True   LL-Null:                       -1249.1
Covariance Type:            nonrobust   LLR p-value:                 6.659e-56
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -8.4975      0.808    -10.522      0.000     -10.080      -6.915
male                0.5008      0.122      4.115      0.000       0.262       0.739
age                 0.0631      0.007      8.449      0.000       0.048       0.078
education          -0.0670      0.056     -1.207      0.227      -0.176       0.042
currentSmoker      -0.0011      0.178     -0.006      0.995      -0.350       0.348
cigsPerDay          0.0192      0.007      2.680      0.007       0.005       0.033
BPMeds              0.2390      0.255      0.938      0.348      -0.261       0.739
prevalentStroke     0.4054      0.512      0.792      0.428      -0.598       1.409
prevalentHyp        0.2909      0.154      1.888      0.059      -0.011       0.593
diabetes           -0.1830      0.372     -0.492      0.623      -0.912       0.546
totChol             0.0028      0.001      2.210      0.027       0.000       0.005
sysBP               0.0159      0.004      3.731      0.000       0.008       0.024
diaBP              -0.0040      0.007     -0.559      0.576      -0.018       0.010
BMI                 0.0060      0.014      0.421      0.674      -0.022       0.034
heartRate          -0.0045      0.005     -0.959      0.338      -0.014       0.005
glucose             0.0094      0.003      3.591      0.000       0.004       0.015
===================================================================================

In [28]:
logistic_regression_final.predict(df_test)

3799    0.322151
1236    0.257555
1364    0.070094
2050    0.187204
2525    0.059173
          ...
2843    0.086654
3180    0.124386
3811    0.055961
4231    0.220887
2552    0.085480
Length: 732, dtype: float64